[package]
name = "deploy"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
ssh2 = "0.9"
tokio = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
indicatif = { workspace = true }
util = { path = "../util" }
