[package]
name = "cli"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
sdkcore = { workspace = true }
util = { workspace = true }
config_mgr = { workspace = true }
deploy = { workspace = true }
provision = { workspace = true }
clap = { workspace = true }
crossterm = { workspace = true }
anyhow = { workspace = true}
tokio = { workspace = true }
unicode-width = { workspace = true }
dirs = "5"
